### ISSUE TITLE
Fails with Build.PL, passes with Makefile.PL (version 0.003)

### ISSUE THREAD

**Issue by andk** [diocles/Test2-Tools-xUnit#1]
Build.PL runs more tests than Makefile.PL. The failing test is always t/fixtures/unhandled-attribute.t which is not run by MakeMaker, only by Module::Build.

See the links to all reports by invoking command: http://analysis.cpantesters.org/reports_by_field?distv=Test2-Tools-xUnit-0.003;field=meta%3Aoutput_from

**Comment by colinnewell** [comment]
It looks like Test2::Suite solves this problem by in-lining the tests that are intercepted in the actual tests.  We could probably write a quick script to suck them up and remove the fixture tests that are getting caught by other tools.
