### ISSUE TITLE
MYMETA must not be included

### ISSUE THREAD

**Issue by chorny** [diocles/Test2-Tools-xUnit#7]
Your distribution (CVLIBRARY/Test2-Tools-xUnit-0.005.tar.gz) contains files MYMETA.json/MYMETA.yml/Makefile. These files must not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is for an old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=CVLIBRARY and contact me.
P.P.S. This report was generated automatically.

**Comment by colinnewell** [comment]
Thanks for the bug report.  I have cleaned up our build process to prevent that happening, and pushed a new release to CPAN.
